alias x=exit
alias random_music="music_playlist"
alias music="music_playlist"
alias music="music_playlist"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron"
alias vgrepsrc="cd /Users/sjangra/go/src/github.com/vrothberg/vgrep"
alias lg=lazygit
alias pylint="python3 -m pylint"
export AWS_PROFILE=dvc_sandeep
alias docekr=docker
alias -g ...=../../
alias -g ....=../../../
alias gcpm="git cherry-pick -m 1"
alias stonks="mpv /Users/sjangra/scam_1992_title.mkv"
